<a href="https://colab.research.google.com/github/tkarthikeyan-tk/ml/blob/main/sample1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np

# create an array using np.array()
array1 = np.array([1, 3, 5])
print("np.array():\n", array1)

# create an array filled with zeros using np.zeros()
array2 = np.zeros((3, 3))
print("\nnp.zeros():\n", array2)

# create an array filled with ones using np.ones()
array3 = np.ones((2, 4))
print("\nnp.ones():\n", array3)

np.array():
 [1 3 5]

np.zeros():
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

np.ones():
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
